name: Tests

on:
  push:
    branches:
      [ "main", "qa", "develop" ]
  pull_request:
    branches:
      [ "main", "qa", "develop" ]
  schedule:
    - cron: '0 7 * * 1-5'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }} - ${{ matrix.parallel }}

    steps:
    - name: MysqlSetUP
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3800 # Optional, default value is 3306. The port of host
        container port      : 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server    : 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version       : '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database      : 'laravelXDB' # Optional, default value is "test". The specified database which will be create
        # mysql root password :  # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user          : 'laravelXadmin' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password      : 123456 # Required if "mysql user" exists. The password for the "mysql user"
      run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
    - name: MysqlSetUPLaravelUser
      run: mysql -ularavelXadmin -p123456 -h127.0.0.1 -e 'SELECT version()'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions : zip, fileinfo
        tools      : composer:v2
        coverage   : none
    - name: Copy .env
      run : php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run : composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run : php artisan key:generate
    - name: Directory Permissions
      run : chmod -R 777 storage bootstrap/cache
    - name: npm
      run : npm install
    - name: brazzers
      run : php artisan breeze:install blade --dark

#    - name: enable mysql
#      env:
#        DB_CONNECTION: mysql
#        DB_HOST      : 127.0.0.1
#        DB_PORT      : 3306
#        DB_DATABASE  : laravel_db
#        DB_USERNAME  : root
#        DB_PASSWORD  : ''
#      run : sudo service mysql start
    - name: pest
      run : ./vendor/bin/pest


